amida-tech/greyscale

backend/app/bootstrap.js
backend/app/db_bootstrap.js

- bootstrap.js: a pg client checks to see if the named db from
config.js exists. The DB will be created if necessary. Then the
greyscale table set will be created, if necessary
- db_bootstrap.js: cleanup comments and formatting
This commit will later need to be extended to create tenant-specific
tables.

GREY-9 Create automated bootstrap process for Postgres database

---

backend/.gitignore
client/Gruntfile.js
client/app/index.html
client/app/scripts/app.js
client/app/scripts/controllers/visualization.js
client/app/styles/main.scss
client/app/views/controllers/visualization.html
client/app/views/directives/sidebar.html
client/bower.json

Create a drop-in view for a map visualizations directive. Also corrects the issue with FontAwesome failing to render.

GREY-44 and GREY-33

---

backend/app/bologger.js
backend/app/controllers/users.js
backend/app/queries/common.js
backend/db_dump/essences.sql
backend/db_dump/patches/20160329-01-essences.sql
backend/db_dump/patches/20160329-02-UserGroups.sql

Feature #53 Tracing

---

backend/Dockerfile
backend/Gruntfile.js
backend/config_etalon.js
backend/dev-Dockerrun.aws.json
client/Gruntfile.js
client/docker-nginx.conf

Settings for adding memcached to the elastic beanstalk deployment using multicontainer Docker. Untested, but needs to be merged into `current` to deploy to Jenkins.

Js new docker

---

backend/db_dump/public.sql
backend/db_dump/sceleton.sql

This would remove the necessity of pgAdmin. Let me know if you see any issues with restoring from this .sql versus the .backup. I'm not sure if there's a tool to `diff` databases, but that would be the ideal check.

convert most recent .backup files to .sql dumps

---

backend/app/error/err_code.json
docker-compose.yml

We may need more in the future—for example, for number of containers
running in different environments.
Also fixed some annoying typos in the error code map.

docker-compose env vars

---

backend/app/controllers/products.js

Add an OptIndex field to CSV dumps containing the 1/2/3, a/b/c or A/B/C formatted index of the selected option for multichoice questions, as shown in the frontend

Add OptIndex field to CSV dumps

---

backend/app/controllers/products.js

For a given question/target/workflowStep triple, we were previously using the following logic to find the (most recent) answer data:
- SurveyAnswer with the max version *with equal workflowStep*
This was not the logic being used by the frontend, both for storing and retrieving data. We're now using the following logic in the CSV export, which I believe matches the frontend (@sean please confirm if you are able to):
- If a SurveyAnswer with equal workflowStep and null version exists, use that one (draft answers have null version, so if a draft has been saved then always pull answers from there).
- Otherwise use the SurveyAnswer with the max version with workflowStep <= desired workflowStep. This handles the case of the user going back to a previous step and modifying answers (the current …

Fix most recent data not being in CSV (GREY-349)

---

backend/app/services/products.js

fixed - No notification when task activated

GREY-351 fixed

---

client/app/styles/_tables.scss

found that this was missed while PR conflict resolving

Hot fix/grey 232 bug fix for hidden month in datepicker

---

backend/app/controllers/products.js

As per client's request, see jira ticket GREY-296

Add boolean variable to CSV download indicating if answer is current step (GREY-296)

---

backend/app/mc_helper.js

Added prefix for each memcache keys

added memcache prefix

---

backend/app/controllers/products.js

Reverts amida-tech/greyscale#153 Reverting merge into current as QA uncovered a ton of bugs.

Revert "Add boolean variable to CSV download indicating if answer is current step (GREY-296)"

---

backend/app/controllers/discussions.js
client/app/scripts/directives/survey-discussion.js

Reverts amida-tech/greyscale#135 accidental merge.

Revert "Hot fix/grey 307"

---

README.md

Reverts amida-tech/greyscale#179

Revert "update README with local Docker instructions"

---

client/app/greyscale.core/scripts/services/greyscale-rest.js
client/app/scripts/directives/survey-discussion.js

Reverts amida-tech/greyscale#198

Revert "Hb feature/grey 388 improve UX for flagging in discussions"

---

client/app/scripts/controllers/modals/modal-comment-full-screen.js
client/app/scripts/controllers/policy-edit.js
client/app/scripts/controllers/policy-review.js
client/app/scripts/directives/fb-policy.js
client/app/scripts/directives/survey-form-field.js
client/app/styles/_panels.scss
client/app/views/directives/fb-policy.html
client/app/views/directives/gs-context-menu.html

Reverts amida-tech/greyscale#230

Revert "add ability to comment in edit mode"

---

client/app/views/modals/product-workflow-row-form.html

https://jira.amida-tech.com/browse/GREY-564

Hide/remove Survey Access and Permissions from all users in Workflow template

---

client/app/greyscale.tables/scripts/services/greyscale-my-tasks-finished.js
client/app/greyscale.tables/scripts/services/greyscale-my-tasks-future.js
client/app/greyscale.tables/scripts/services/greyscale-my-tasks.js
client/app/scripts/controllers/project-setup.js
client/app/views/controllers/home.html

Related issue: https://jira.amida-tech.com/browse/GREY-403
Screenshots:

Rename "Projects" to "Medical Policy Review"

---

client/app/greyscale.tables/scripts/services/greyscale-project-products.js
client/app/styles/_general.scss
client/app/views/modals/modal-form.html

Resolves:
https://jira.amida-tech.com/browse/GREY-405
https://jira.amida-tech.com/browse/GREY-555

/projects language changed to reflect "policy" language + required form fields asterisk UI fix.

---

client/app/greyscale.tables/scripts/services/greyscale-groups.js

https://jira.amida-tech.com/browse/GREY-559

Hide group ID on Edit Group menu

---

client/app/greyscale.tables/scripts/services/greyscale-project-products.js

First bullet point: https://jira.amida-tech.com/browse/GREY-544

Add warning when user changes project status to 'completed'

---

client/app/greyscale.core/scripts/config/greyscale-side-menu.js
client/app/scripts/controllers/dashboard.js
client/app/scripts/controllers/project-setup.js
client/app/views/directives/sidebar.html
client/i18n/en.json

Affects:
https://jira.amida-tech.com/browse/GREY-239
https://jira.amida-tech.com/browse/GREY-238
https://jira.amida-tech.com/browse/GREY-406

Language changes.

---

client/app/greyscale.tables/scripts/services/greyscale-project-products.js

See comment on https://jira.amida-tech.com/browse/GREY-405

Remove "subjects" under settings on /projects.

---

client/app/views/modals/modal-form.html

https://jira.amida-tech.com/browse/GREY-578
No screen shot - just look at code - it is removed.

Remove POLICY from top of modals.

---

client/app/views/controllers/policy-edit.html

https://jira.amida-tech.com/browse/GREY-579
Removed the related boxes on the left as well.

Hide 'Edit Field' and 'Add new field' boxes on /policy/edit/<id>

---

client/app/views/controllers/home.html

https://jira.amida-tech.com/browse/GREY-581

Remove comment causing error on `grunt build`

---

client/README.md

Read Me Updates regarding first-time installation of Indaba Project

ReadMe Updates

---

client/app/greyscale.tables/scripts/services/greyscale-users.js

Jira Ticket: https://jira.amida-tech.com/browse/GREY-614
URL: http://localhost:8081/#/users/list
Description: Remove anonymous option from User Management

GREY-614 Remove anonymous option from User Management

---

client/app/scripts/controllers/dashboard.js
client/app/scripts/directives/sidebar.js

https://jira.amida-tech.com/browse/GREY-616
URL: http://localhost:8081/#/
Fix Main Menu & Cookie Value Integration

GREY-616 Fix Main Menu & Cookie Value Integration

---

client/app/scripts/controllers/pm-dashboard-product.js
client/app/views/controllers/pm-dashboard-product.html

URL: http://localhost:8081/#/pm/2
JIRA: https://jira.amida-tech.com/browse/GREY-629
Description: Fix Nomenclature bugs on Project Dashboard page

GREY-629 Fix Nomenclature bugs on Project Dashboard page

---

client/app/greyscale.tables/scripts/services/greyscale-my-tasks-finished.js
client/app/greyscale.tables/scripts/services/greyscale-my-tasks-future.js
client/app/greyscale.tables/scripts/services/greyscale-my-tasks.js
client/i18n/en.json
client/i18n/es.json
client/i18n/fr.json
client/i18n/ru.json

Clean up tasks page
https://jira.amida-tech.com/browse/GREY-632
http://localhost:8081/#/tasks

GREY-632 Clean up tasks page

---

client/app/greyscale.tables/scripts/services/greyscale-product-workflow.js

Rows in the Workflow Template editor are now draggable for both existing and new templates
https://jira.amida-tech.com/browse/GREY-622
Go to http://localhost:8081/#/workflow-templates, edit a template and make sure you can drag the different steps around to order them.

Make rows draggable in Workflow Template editor for existing templates

---

client/app/scripts/app.js
client/i18n/en.json
client/i18n/es.json
client/i18n/fr.json
client/i18n/ru.json

Fix Wording 
https://jira.amida-tech.com/browse/GREY-621
http://localhost:8081/#/projects

GREY-621 Change Wording,

---

client/app/views/modals/policy-comment.html

Fix Comment Dialog
https://jira.amida-tech.com/browse/GREY-617
http://localhost:8081/#/policy/review/1/task/3

GREY-617 Fix Comment Dialog

---

client/app/scripts/controllers/modals/modal-comment-full-screen.js
client/app/views/modals/comment-full-screen.html

Fix Comment Review Dialog
https://jira.amida-tech.com/browse/GREY-618
http://localhost:8081/#/policy/review/1/task/3

GREY-618 Fix Comment Review

---

client/app/index.html
client/app/scripts/directives/policy-block.js
client/app/views/directives/policy-block.html
client/bower.json
client/test/karma.conf.js

add print policy link on edit policy page
https://jira.amida-tech.com/browse/GREY-608
http://localhost:8081/#/policy/edit/3

GREY-608 Print a policy on edit policy page

---

client/app/greyscale.core/scripts/config/greyscale-globals.js
client/i18n/en.json
client/i18n/es.json
client/i18n/fr.json
client/i18n/ru.json

Add two New Section in Create Policy Section
https://jira.amida-tech.com/browse/GREY-609
http://localhost:8081/#/policy/edit/

GREY-609 Fix Policy Creat Section

---

client/app/views/controllers/pm-dashboard-product.html
client/i18n/en.json
client/i18n/es.json
client/i18n/fr.json
client/i18n/ru.json

Fix Green Box
https://jira.amida-tech.com/browse/GREY-633
http://localhost:8081/#/pm/2

GREY-633 Fix Green Box

---

backend/app/controllers/surveys.js
backend/app/router.js
backend/app/services/surveys.js
client/app/greyscale.rest/scripts/services/greyscale-survey.js
client/app/scripts/controllers/modals/modal-select-review-versions.js
client/app/scripts/controllers/pm-dashboard-product.js
client/app/scripts/services/greyscale-modals.js
client/app/views/modals/select-policy-version.html
client/i18n/en.json
client/i18n/es.json
client/i18n/fr.json
client/i18n/ru.json

Added New "Final Version" in Version Download Dialog,
Updated Backend according to it,
https://jira.amida-tech.com/browse/GREY-612
http://localhost:8081/#/pm/27 (Policy that is in complete status)

GREY-612 Add Final Version To the Download, Updated Backend

---

client/app/views/directives/policy-block.html

Fix Policy Block
https://jira.amida-tech.com/browse/GREY-583
http://localhost:8081/#/policy/edit/

GREY-583 Fix Policy Block

---

client/app/greyscale.wysiwyg/scripts/greyscale.wysiwyg.js
client/app/index.html
client/app/styles/_wysiwyg.scss

Fix Text Editor, add new color buttons
https://jira.amida-tech.com/browse/GREY-610

GREY-610 Fix Text Editor

---

client/app/greyscale.core/scripts/config/greyscale-globals.js
client/app/greyscale.tables/scripts/services/greyscale-project-products.js
client/i18n/en.json
client/i18n/es.json
client/i18n/fr.json
client/i18n/ru.json

Fix Project Listing and & Add New Project Modal Dialog
https://jira.amida-tech.com/browse/GREY-625
http://localhost:8081/#/projects

GREY-625 Fix

---

client/app/greyscale.tables/scripts/services/greyscale-workflow-templates.js

Change sorting for cloned item
https://jira.amida-tech.com/browse/GREY-574
http://localhost:8081/#/workflow-templates

GREY-574 Change Sorting for Clone Function

---

client/app/greyscale.tables/scripts/services/greyscale-product-workflow.js
client/app/scripts/controllers/modals/modal-product-workflow.js
client/app/views/modals/product-workflow-row-form.html

http://localhost:8081/#/workflow-templates
https://jira.amida-tech.com/browse/GREY-573

GREY-573 Remove Role in the Workflow Template

---

client/app/scripts/controllers/policy-edit.js

Remove Legislation Between Description & Reference
https://jira.amida-tech.com/browse/GREY-609
http://localhost:8081/#/policy/edit/8

Remove Legislation Between Description & Reference

---

client/app/greyscale.wysiwyg/scripts/greyscale.wysiwyg.js

Clear Format Function
https://jira.amida-tech.com/browse/GREY-611

GREY-611 Clear Format Function

---

client/i18n/en.json

Fix Translation
https://jira.amida-tech.com/browse/GREY-652
http://localhost:8081/#/policy/version/1/

GREY-652 Fix Translation

---

client/i18n/en.json

Change Policy Text from Descriptions to Description
https://jira.amida-tech.com/browse/GREY-655
http://localhost:8081/#/policy/edit/

GREY-655 Fix Policy Text

---

backend/app/services/surveys.js

Fix Space Issue
https://jira.amida-tech.com/browse/GREY-657
http://localhost:8081/#/policy

GREY-657 Fix Space Issue

---

client/app/scripts/controllers/dashboard.js
client/app/scripts/controllers/modals/modal-comment-full-screen.js
client/app/scripts/directives/gs-message.js
client/app/scripts/directives/policy-discussion.js

https://jira.amida-tech.com/browse/GREY-618

GREY-618 Fix Tagged In User

---

client/app/scripts/directives/policy-block.js

Add Line Number
https://jira.amida-tech.com/browse/GREY-608
[policy (15).pdf](https://github.com/amida-tech/greyscale/files/642626/policy.15.pdf)

GREY-608 Add Line Number

---

client/app/scripts/controllers/modals/modal-product-workflow.js

Fix Project Page,
https://jira.amida-tech.com/browse/GREY-448
http://localhost:8081/#/pm/8

GREY-448 Fix Angular Data Compatibility Error

---

client/app/greyscale.tables/scripts/services/greyscale-users.js
client/app/scripts/controllers/users-list.js
client/app/views/controllers/users-list.html

Add User Group FIlter to User List Page
https://jira.amida-tech.com/browse/GREY-572
http://localhost:8081/#/users/list

GREY-572 Add User Group Filter to User Page

---

client/app/greyscale.tables/scripts/services/greyscale-project-products.js
client/app/scripts/controllers/modals/modal-product-task.js
client/app/scripts/services/greyscale-modals.js
client/app/views/modals/product-task.html
client/i18n/en.json
client/i18n/es.json
client/i18n/ru.json
client/test/karma.conf.js

Change Task Page to Modal
https://jira.amida-tech.com/browse/GREY-450
http://localhost:8081/#/projects

GREY-450 Change Task Page to Modal

---

client/app/scripts/directives/gs-message.js
client/i18n/fr.json

Fix Comment Quote
https://jira.amida-tech.com/browse/GREY-628
http://localhost:8081/#/policy/edit/9

GREY-628 Fix Quote Change

---

client/app/index.html
client/app/scripts/directives/policy-block.js
client/app/vendors/jspdf/jspdf.js

Fix JSPDF Library & Place it Under Vendor Folder
https://jira.amida-tech.com/browse/GREY-661

GREY-661 Fix JSPDF Library & Place it Under Vendor Folder

---

client/app/views/controllers/users-list.html

Fix User Page
https://jira.amida-tech.com/browse/GREY-572
http://localhost:8081/#/users/list

GREY-572 Fix User List Search Control

---

client/app/views/modals/comment-full-screen.html
client/i18n/en.json
client/i18n/es.json
client/i18n/fr.json
client/i18n/ru.json

Update Modal Dialog Tagged User Text
https://jira.amida-tech.com/browse/GREY-618

GREY-618 Update Texts

---

client/app/greyscale.tables/scripts/services/greyscale-project-products.js
client/i18n/en.json
client/i18n/es.json
client/i18n/fr.json
client/i18n/ru.json

Fix Project Page
https://jira.amida-tech.com/browse/GREY-625
http://localhost:8081/#/projects

GREY-625 Fix Description

---

backend/app/services/surveys.js

Final Version Doc Download Fix
https://jira.amida-tech.com/browse/GREY-612
http://localhost:8081/#/pm/43

GREY-612 Fix Backend End Point

---

backend/db_setup/data.indaba.sql
backend/db_setup/schema.indaba.sql

Applied outstanding database migrations and recreated seed files.

updated plaintext sql db seed files

---

client/app/index.html
client/bower.json
client/test/karma.conf.js

This PR fixes a problem with the socket.io inclusion that results in window.io not being defined.

fix socket.io from bower reference

---

README.md

Just a suggested tweak for readability.

Fix section headers and separators

---

README.md
backend/.gitignore
backend/config.js
backend/lib/passport_token.js
backend/package.json
backend/test/task_dev.integration.js

Make it possible to for a particular user by specifying a token in environment variable (INDABA_USER_TOKEN).

Authentication thru config token

---

backend/app/controllers/projects.js

Removes the restriction in place that prevents multiple projects per organization.

Removed single project restriction.

---

backend/app/controllers/users.js

Reverts amida-tech/greyscale#346

Revert "Feature/inba 304 correction"

---

backend/app/controllers/users.js

Very small change needed for the similarly named inba-350 client branch.

Tiny change to actually return something.

---

backend/app/controllers/users.js

Reverts amida-tech/greyscale#364

Revert "Tiny change to actually return something."

---

backend/app/controllers/discussions.js
backend/app/controllers/projects.js
backend/app/controllers/uoas.js
backend/app/models/tasks.js
backend/app/router.js
backend/app/services/common.js
backend/db_setup/schema.indaba.sql

#What does this PR do
- Tighten's up code a little bit more and reduces code redundancy
#How can I test this PR
-Thoroughly review the code and throughly check these end points to ensure they work as expected
DELETE: `http://localhost:3005/testorg/v0.2/projects/projectId/users/userId`
POST:  `http://localhost:3005/testorg/v0.2/projects/:projectId/users`
PUT: `http://localhost:3005/testorg/v0.2/discussions/resolve/questionId`
#Tickets associated with this PR
[343](https://jira.amida-tech.com/browse/INBA-343)
[344](https://jira.amida-tech.com/browse/INBA-344)
[345](https://jira.amida-tech.com/browse/INBA-345)
[346](https://jira.amida-tech.com/browse/INBA-346)
#Background Context
- You need to have Indaba backend running
- Make sure you have the right data in the right tables

made small changes and fixes to clean up code and tighten security

---

backend/app/controllers/users.js

Fix for 350

---

backend/app/controllers/groups.js

Change when creating a new user group that adds that user group to the ProjectUserGroups table.

Change that adds groups to the ProjectUserGroups.

---

backend/app/controllers/products.js

You can change this if you want, but I need this to return something.

I need this to return something already.

---

backend/app/controllers/projects.js

Combination bad param and questionable query. Test carefully.

Fix for the update tasks.

---

backend/app/controllers/projects.js

Feel free to change as long as it returns something.

INBA-211 Part 2 JSON RETURNS!

---

backend/app/models/tasks.js
backend/db_setup/schema.indaba.sql

Minor change that creates and allows editing to the Tasks table, with a new column called "assessmentId." This is needed for a matching indaba frontend change.

Schema changes to allow for assessmentIds.

---

backend/app/controllers/users.js

changed let to var

---

backend/app/controllers/groups.js

This PR amends the `PUT /groups/{groupID}` endpoint to:
1. Make the title body parameter optional and update it if it passed
2. Allow the caller to supply a `userId` body argument and update the members of the group if it is supplied

Feature/INBA-532 Support group membership update

---

backend/app/controllers/uoas.js

Removed isComplete reference from uoas delete

removed isCompelte from deleting UOA's

---

backend/app/controllers/tasks.js

checked for deleted workflows before pulling minStepPositionQuery

checked for deleted workflows before pulling minStepPositionQuery

---

backend/app/controllers/products.js
backend/app/services/common.js

Advances workflow from one stage to another. 
Calling the `productUOAmove` should advance the workflow from one state to another:
`v0.2/products/:id/move/:uoaid`

Task/inba 536/complete task

---

backend/app/controllers/users.js
backend/config.js

Added temp solution for created users to log in.
Put password as an `env` variable that way Kate can decide on what she wants it to be.

added temp solution for users to login with temp password

---

backend/app/controllers/tasks.js

Backend to the Frontend didn't need to be a trilogy, man.

INBA-618: Tweak that returns the entire task and not just the Id.

---

backend/app/controllers/users.js
backend/config.js

Removed user temp password from greyscale

removed temp password

---

aws-fluentd-k8s.yml

Readme updates and documentation to come

add daemonset config

---

backend/app/controllers/discussions.js
backend/app/controllers/groups.js
backend/app/controllers/products.js
backend/app/controllers/projects.js
backend/app/controllers/uoas.js
backend/app/controllers/workflows.js
backend/app/models/projects.js
backend/app/router.js
backend/app/services/common.js
backend/db_setup/schema.indaba.sql

This PR adds a `lastUpdated` column to the projects table which is updated in cases enumerated [here](https://github.com/amida-tech/indaba-client/pull/365), and adds an endpoint for explicitly updating the value due to a survey change.

Bug/INBA-484 Last Updated

---

backend/app/controllers/tasks.js
backend/test/util/shared-integration.js

In a world... where the task matrix has one stage and one task. And that task is completed. Then another stage is added... and another task is assigned. That task... did not copy the prior task's assessment answers, thus showing them when the assigned user logs in to view that task.
Until now.
Starring Jacob Sachs as Kevin Costner. And Perry Ogwuche as Jacob Sachs. 
INBA-561. Coming soon to a develop branch near you.

INBA-561/ Copy assessment

---

backend/app/controllers/discussions.js
backend/app/controllers/notifications.js
backend/app/controllers/system_messages.js
backend/app/services/common.js
backend/app/services/messages.js
backend/views/emails/discussion.html
backend/views/notifications/entry.html

Add ability for users to get internal messages as well as emails when they get flagged. 
To test:
- Go through steps to create project, assign task etc.
- Comment on a question and notify user.
- Log in as that user and make sure they get notification on Indaba and they also get an email.

task/INBA-529-PO-Add Message Services (notify) call from Discussions and Tasks

---

backend/app/controllers/users.js
backend/app/services/common.js

This PR accompanies the front-end PR here https://github.com/amida-tech/indaba-client/pull/386 and details notes including a risk flag are provided there.
[INBA-700](https://jira.amida-tech.com/browse/INBA-700)

Bug/INBA-700 Resend invite

---

backend/app/controllers/products.js

Create a survey with a bullet point answer. Answer it and give it a few fields worth. Save and complete the task.
Go export the task data. The data should appear with arrows between answers, like so:

INBA-776 / Tweak that has json2csv handle characters correctly.

---

backend/app/controllers/products.js
backend/app/services/survey.js

Returns a new CSV that includes the commentHistory. The most **current** comment will be returned as part of project data. This CSV only handles the older comments. To generate anything other than a blank CSV, you'll have to create some "Comment and Review" stages, at least two.

INBA-773 / Change that adds the param for including comments to the survey call,

---

backend/app/controllers/products.js

This adds `questionIndex` and `weight` to the fields greyscale expects from the survey service export, parses file information from the meta field if it exists, and includes all of them in the resulting csv.
Ticket: https://jira.amida-tech.com/browse/INBA-774

Bug/INBA-774 Missing export fields

---

backend/config.js
backend/lib/mailer.js

replaced gmail info with env vars

INBA-788/replaced gmail info with env vars

---

backend/app/controllers/products.js

added subject to flags csv
- Export data and make sure the flagsCSV files comes with a Subject column and the appropriate data
Ticket: https://jira.amida-tech.com/browse/INBA-766

added subjec to flags csv

---

backend/app/app-generator.js
backend/app/controllers/projects.js

Fixes `HttpError` by adding the `next` parameter to `app.use()`
https://jira.amida-tech.com/browse/INBA-844
Easiest way is to activate a project that has a survey in draft mode and make sure you get the right error displayed.

added next to add.use function and removed console log statements

---

backend/app/controllers/groups.js

Allows deletion of userGroup when a project is made inactive
https://jira.amida-tech.com/browse/INBA-794
Switch frontend branch to: `bug/inba-794-cb-delete-user-group-inactive`
- Try deleting group of a project that is active (you shouldn't be able to)
- Make the project inactive and try again- this should work

INBA-794 / added check for active or inactive project before deleting

---

backend/app/controllers/projects.js

Adds check for isNull when activating a project
https://jira.amida-tech.com/browse/INBA-741
- Delete a stage from an inactive project
- Try activating the project

INBA-741 / added check for isNull on stages when activating a project

---

backend/app/app-generator.js

Pairs with INBA-811 indaba-client side.

INBA-811 / Added new headers for handling IE11's aggressive caching.

---

backend/app/controllers/projects.js
backend/app/error/index.js

INBA-851 / Returns empty array if no projects found. Also removes console logs from

---

backend/config.js
backend/views/emails/activate_project.html
backend/views/emails/activate_task.html
backend/views/emails/assign_task.html
backend/views/emails/discussion.html
backend/views/notifications/activate_project.html
backend/views/notifications/activate_task.html
backend/views/notifications/assign_task.html

Adds survey name to email messages
https://jira.amida-tech.com/browse/INBA-757
- Create task, activate project, create discussion and make sure email has survey name in it
See comment in ticket

INBA-757/added survey name to email messages

---

backend/views/emails/assign_task.html
backend/views/notifications/assign_task.html

Modifies URL in email to route to task page
https://jira.amida-tech.com/browse/INBA-755
- Assign a task to a user
- Verify that the email the user receives has the correct URL to view their tasks.

INBA-755/modify url to route to task page

---

backend/config.js

Update for version.

---

backend/app/router.js

Prevent Regular User from Fetching Endpoints
https://jira.amida-tech.com/browse/INBA-881
From front-end: Login into indaba with regular user try to go to 
`/uoas`
`projects/${projectId}`
you should be rerouted. 
'rights_all_access' is only given to users with the privilege to view all.

INBA-881 / Bug/fixed routes so regular users cannot access.

---

backend/app/services/survey.js

Reverts amida-tech/greyscale#492, awaiting SER-194.

Revert "INBA-860 / Change endpoint for assessment-answers"

---

backend/app/router.js

My fault for forgetting to check this.

Remove security check on projects. Needed because 881 broke it.

---

backend/app/controllers/users.js

Goes with the front end ticket at [here.](https://github.com/amida-tech/indaba-client/pull/507)

Change that returns errors if the user is already in the system or in

---

backend/app/controllers/projects.js
backend/app/services/common.js

[INBA-800] Adds a check for flag histories, primarily for the PMs.

---

backend/app/services/common.js
backend/app/services/survey.js

refactors a request code into it's own function. 
indaba-739
check that you can still create and edit a survey.

refactored Common.js request
