- backend/package.json
- client/Gruntfile.js
- client/package.json
- client/test/karma.conf.js
- update all deps and install peer deps explicitly for node 5 and npm 3
- specify node 5 in the package.json engines field
- ignore Plotly.js in the test wiredep, as something is breaking in
PhantomJS
> GREY-45 update packages for Node 5

- backend/Dockerfile
- client/Dockerfile
it wasn’t as bad as I remembered, but it’s generally better to have
copies and adds as the last thing in your Dockerfile, to allow as much
cacheing as possible
> minor optimization

- backend/app/controllers/products.js
Draft answers have a null version, in postgres (NULL = NULL) is null rather than true so joins were failing. Test by exporting client's product 2 to CSV, and verifying answers are present for Bangladesh step 4.
> Fix draft answers not appearing in CSV export (GREY-343)

- client/app/greyscale.core/scripts/config/greyscale-side-menu.js
https://jira.amida-tech.com/browse/GREY-530
See lack of tab:
> Remove Visualizations tab from UI

- client/app/views/controllers/policy-edit.html
In the Policy Edit view (accessible only by admins), make the Policy Discussion comments box on the right hand side scroll with the window (consistent with the standard Policy view).
https://jira.amida-tech.com/browse/GREY-627
Go to http://localhost:8081/#/policy/edit/1 as an admin and check the Discussion box remains at the top of the window as you scroll down.
> Scroll comments on admin policy edit view

- client/app/views/directives/fb-policy.html
The policy edit form (for both new and existing policies) had duplicate rich text boxes under each section. This PR removes those.
https://jira.amida-tech.com/browse/GREY-635
https://jira.amida-tech.com/browse/GREY-636
Go to http://localhost:8081/#/policy/edit/ and http://localhost:8081/#/policy/edit/1 and expand the COVERAGE/DESCRIPTIONS/etc sections. Verify there's only one rich text box under each one. Either write some text in for a new policy, or modify an existing policy and make sure the updates are still saved.
Go to an existing policy as an admin and highlight some text. Verify you get the new comment menu.
> Remove duplicate text boxes from policy edit form

- client/i18n/en.json
Replace "You has been answered" with "You have already responded to this comment and cannot respond again"
https://jira.amida-tech.com/browse/GREY-630
Respond to a comment on a policy, and then try responding to the same comment again. You should see a grammatically correct English response.
> Fix "You has been answered" copy

- client/app/scripts/directives/gs-message.js
Comments on the admin policy edit page were being incorrectly compared to the current text to see if the policy had been updated. This PR fixes that, meaning comments scroll to the relevant section rather than giving a "Quoted text has changed" warning.
https://jira.amida-tech.com/browse/GREY-628
Go to http://localhost:8081/#/policy/edit/1 as an admin and click on the "FFF" coverage comment. It should scroll to a section in the text, rather than giving you a warning.
> Correctly scroll to nonedited comments on admin policy edit page

- client/app/greyscale.tables/scripts/services/greyscale-project-surveys.js
- client/app/scripts/controllers/policy-edit.js
- client/app/views/controllers/pm-dashboard-product.html
- client/app/views/controllers/policy-edit.html
- client/app/views/controllers/project-setup-products.html
- client/app/views/directives/policy-block.html
Nurses were getting confused by the In Draft/Complete policy distinction, so this PR marks all policies as complete and removes the status from everywhere in the frontend.
https://jira.amida-tech.com/browse/GREY-620
Go to http://localhost:8081/#/projects and confirm you see no mention of In Draft/Complete in the Policy column.
Go to http://localhost:8081/#/pm/2 and confirm the same.
Go to http://localhost:8081/#/policy and confirm there's no status column.
Go to http://localhost:8081/#/policy/edit/1 and check the version is listed as -1 not Draft. No future policies will be
marked as In Draft so no policy will show as -1, this just confirms the Draft/Complete check here is gone. Make sure the form only contains a Submit button, not a Save one.
Go to http://localhost:8081/#/policy/edit/ to …
> Remove In Draft/Complete policy distinction

- backend/app/models/project_users.js
- backend/db_setup/schema.indaba.sql
#What's this PR do?
Creates a new table- ProjectUsers
#Related JIRA tickets:
[334](https://jira.amida-tech.com/browse/INBA-334)
#How should this be manually tested?
- Run `psql -h localhost -U indabauser indaba < schema.indaba.sql` 
- Look in your database, you should see ProjectUsers created. And it should have a constraint that -
- looks like this if you look at the SQL 
`CONSTRAINT "ProjectUsers_projectId_fkey" FOREIGN KEY ("projectId")
REFERENCES test."Projects" (id) MATCH SIMPLE`
#Any background context you want to provide?
Screenshots (if appropriate):
> created new table ProjectUsers and added constraints

- backend/app/controllers/projects.js
- backend/app/models/project_users.js
- backend/db_setup/schema.indaba.sql
This PR references the users from the ProjectUsers table when a Project is selected instead of getting them from the Organization table. 
To Test:
Populate the Databases (Projects, Users, Organization) with data and select one project:
`/v0.2/projects/:id`
> added testorg to the indaba user

- backend/app/controllers/projects.js
When the admin logs into the system, they get a listing of all the projects they've created. Going forward, this object should now return a surveyId with it, be it an integer or a null. This surveyId will be used to get the survey list from the survey microservice. 
To test, deploy and log in as testadmin. Ensure that the projects object returned on the first page (the project list) includes a surveyId with each project.
> INBA-403: Return surveyIds with the listAll project list.

- backend/app/controllers/tasks.js
Adds a check in `getTasksByProjectId()` to make sure project with ID exists before trying to pull tasks.
https://jira.amida-tech.com/browse/INBA-391
- Use postman to hit: `http://localhost:3005/testorg/v0.2/tasks-by-proj-id/2` if this project doesn't exist in the `Projects` table you should get an error letting you know project doesn't exist. 
- Ensure that this works with indaba-client
Don't forget the auth service - it needs to be running!
> added check for projects before trying to pull tasks by projectID

- backend/app/controllers/tasks.js
This PR changes the http response of `/tasks-by-user-id/:userId` to 204 from 403 when a user has no tasks.
To test, make a request to `/tasks-by-user-id/:userId` for a valid user with no tasks. The response should be HTTP 204 and not HTTP 403
> Bug/INBA-496 Fix http response when user has no tasks

- backend/app/controllers/groups.js
Removes users from a group before deleting the group
[499](https://jira.amida-tech.com/browse/INBA-499)
- Create a project
- Create a group and add users to it
- Try deleting a group with users in it
> Removed user from group before trying to delete Group

- backend/app/controllers/projects.js
- backend/app/controllers/tasks.js
- backend/app/services/common.js
Round 2: Way better implementation.
To Test:
**Explanation: Earlier-in-the-process tasks assigned after later tasks should supersede the latter.**
Create a new project, with users, usergroups, a few subjects and a few stages, preferably 3.
Assign a task to stage 3.
Check the `ProductUOA` table and ensure that a new entry is added, which includes a `currentStepId`.
Assign another task on the same subject as the previous one.
Check the `ProductUOA` table and ensure that a prior entry has changed to an earlier (less) `currentStepId`.
**Explanation: The earlier task should supersede later tasks assigned after.**
On another subject, add a task to stage 1. 
Check the `ProductUOA` table for a new entry.
On the same subject as the prior entry, assign another task to either stage 2 or 3.
Check the …
> Feature INBA-535 - AssignTask Current Step

- docker-compose.yml
@jsachs PR looks good. Creating this PR to merge into the docker-compose PR. Some services were exiting early because their dependencies hadn't started. It looks like this fixed it.
> start dependencies first

- README.md
- backend/.env.example
- backend/app/app-generator.js
- backend/app/controllers/system_messages.js
- backend/app/router.js
- backend/app/services/messages.js
- backend/config.js
Supports sending system generated messages in response to the `/system_messages` endpoint
[INBA-593](https://jira.amida-tech.com/browse/INBA-593)
1. Ensure the message service is running and the three new environment variables are set. They have default values in the development configuration and won't need setting when running locally.
1. Make an authenticated request to `POST /:realm/v0.2/system_messages` with a body json: `{"to": "user1@mail.net", "message": "test message"}`.
1. Check that corresponding rows are created in the message db
I don't sanitize the message body text or the `to` field before sending off to the message service. I'd like someone to check that that's ok. I think it should be since the message service receives the same fields directly from the client.
This …
> Feature/INBA-593 System Generated Messages

- backend/app/app-generator.js
This PR adds an error log to record the original error object from the initial authentication call and continues starting the server if the initial authentication call fails.
> Bug/INBA-641 No halt on system message user auth failure

- backend/app/controllers/tasks.js
- backend/app/services/common.js
[INBA-633](https://jira.amida-tech.com/browse/INBA-633)
This PR adds a `complete` property to tasks returned from the `/tasks-self` endpoint which is calculated from the ProductUOA and WorkflowSteps tables.
Please carefully check the sql queries used in the calculations. The intended logic is:
A task is complete if:
1. The corresponding ProductUOA's `currentStepId` is equal to the Task's `stepId` and the ProductUOA's `isComplete` is true
OR
2. The `position` column of the WorkflowStep corresponding to the ProductUOA's `currentStepId` is higher than the `position` column of the WorkflowStep corresponding to the Task's `stepId`
> Bug/INBA-633 Task complete flag

- backend/app/controllers/tasks.js
- backend/app/services/common.js
This PR adds a function to calculate and add an `active` field to tasks, and adds the field to task objects returned by the self tasks endpoint. This is used by the front end to limit the tasks in the user dashboard to those that are complete or active.
See https://github.com/amida-tech/indaba-client/pull/354
> Bug/INBA-635 Add active field to self tasks

- backend/app/controllers/notifications.js
- backend/app/controllers/users.js
- backend/config.js
- backend/test/util/comparator.js
Fixes the issue with the user.integration test and see.js failing
To test:
- Delete your `indabatestuser` dd, recreate it and run `node seed.js`
- Clear your auth users table and ensure that you only have su@mail.net in there, then run `node_modules/.bin/mocha test/user.integration.js --bail -t 10000` This should pass all tests and create users on both indaba and the auth service
> bug/INBA-644-PO-Fix Failing User.integration test and seed.js

- backend/config.js
Removed indaba@example.com from greyscale
In order for you to run `user.integration` you'll need to have `indaba@example.com` and `su@mail.net` created on the auth service.
> removed sys user so we don't have it showing up on greyscale

- backend/app/controllers/users.js
Prior PRs slightly broke the user invites. When a user was already in a system, it was supposed to just assign them to the project and return the existing user for insertion into the User Lists, displaying a toast pop up like ("The user is already in the system, but we've added them to the project for you..." 
To test, create a project and invite a user who is already in the system but not yet assigned to the project. Ensure that the user appears in the list and you get the toast. Then, invite a brand new user into the project. Ensure that you get the "User invited" toast and the user appears.
> INBA-761 - Need to return existing user too.

- backend/app/controllers/products.js
- backend/package.json
What does this PR do:
- Adds feature to create separate csv for flags 
- Zips both csv's up and sends to the client for download
To Test:
- Create a project, survey, assign task, complete task etc.
- Download the csv from the client
- You should get a zip file containing two csv's- one for the project data and one for just flags
Make sure you have `feature/inba-765-jf-export` running on the front end if it hasn't been merged as well as `feature/ser-29-get-answers-by-question-number` on the surveyService
> task/INBA-766-PO-export-flags - Added functionality to download flags and other project data as a zip file

- backend/app/controllers/projects.js
Changes the project listing to return the projects by the latest updated first, down.
INBA-911
Log in as an admin, check that the projects are ordered from most recently updated to the longest ago.
We don't really use the query aspect of it. But if you can think of any circumstances in which I may be wrong, please check.
> INBA-911 / Orders by last updated on "listAll" of the projects

- backend/app/controllers/tasks.js
A user's assigned tasks will now return based on the task's due date, from earliest to latest.
Also allows the future tasks not to be given to the user on the tasks page.
INBA-929.
INBA-853.
Assign a user several tasks. They can be different projects or the same one, preferably with the individual tasks have different end dates. Log in as that user and confirm that the due dates are ordered. (See screenshot below.)
Also, give a user a task in the future. It should not appear in the list. Change the start date for that particular task in the back end (under the `Tasks` table) and it should then appear when the user refreshs.
Tasks are given an initial end date based on the stage's end date. The task's end date can be changed if the admin goes into the tasks and chooses a new date from the …
> [INBA-929][INBA-853] Change that orders the tasks for a user by due date.
